name: Bedwars
version: bugs_test_ver
api: 1.14.0
main: Bluplayz/Main
author: NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
