name: Bedwars
version: bugs_test_ver
api: 3.0.0-ALPHA6
main: Bluplayz/BedWars
author: NetherTechnology
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
